

<h2>Total des fonds récoltés</h2>
<section id="stats_fonds">
    <canvas id="canvas_fonds" style="display:none"></canvas>
    <img class="canvas" id="canvas_fonds_img" alt="Fonds">
</section>

<h2>Nombres de dons</h2>
<section id="stats_dons">
    <canvas id="canvas_dons"></canvas>
    <img class="canvas" id="canvas_dons_img" alt="Dons">
</section>

<h2>Nombre de projets réalisés</h2>
<section id="stats_rea">
    <canvas id="canvas_rea"></canvas>
    <img class="canvas" id="canvas_rea_img" alt="Rea">
</section>