
<section id="stats_fonds">
    <h2>Total des fonds récoltés</h2>
    <div class="section_main">
        <canvas id="canvas_fonds"></canvas>
        <img class="canvas" id="canvas_fonds_img" alt="Fonds" src="assets/img/white.jpg">
    </div>
</section>

<section id="stats_dons">
    <h2>Nombres de dons</h2>
    <div class="section_main">
        <canvas id="canvas_dons"></canvas>
        <img class="canvas" id="canvas_dons_img" alt="Dons" src="assets/img/white.jpg">
    </div>
</section>

<section id="stats_rea">
    <h2>Rapport dons sur fonds récoltés</h2>
    <div class="section_main">
        <canvas id="canvas_rea"></canvas>
        <img class="canvas" id="canvas_rea_img" alt="Rea" src="assets/img/white.jpg">
    </div>
</section>