

<?php if(!empty($last_project)): ?>
    <h2>Dernier projet</h2>
    <section class="last_proj">

        <div class="solo_prj">
            <div class="img">
                <a href="<?=url('project_get',['id'=>$last_project['id']])?>">
                    <img src="<?= $last_project['image_url'] ?>" alt=""/>
                </a>
            </div>
            <div class="side">
                <h3 class="titre"><?= ucfirst($last_project['titre']) ?></h3>
                <p class="createur">Créateur du projet: <?= $last_project['user_login'] ?></p>
                <p class="category">Catégorie <?= $last_project['category'] ?></p>

                <p class="short"><?= $last_project['resume'] ?></p>
                <p class="stats">
                    <?= $last_project['percent'] ?>% 
                    grâce à <?= $last_project['stats_nb_dons'] ?> donateurs</p>
                <p class="fonds"><?= $last_project['stats_somme_rec'] ?>€ récoltés</p>
                <p class="days"> j-<?= $last_project['days_reste'] ?> </p>

                <div class="module" data-percent="<?=$last_project['percent']>100?100:$last_project['percent']?>"><div></div></div>
            </div>
        </div>

    </section>
<?php endif; ?>



    <h2>Les projets du moment</h2>
<section id="#projects_list">
    <?php foreach($list as $project): ?>
        <?php include __DIR__.'/../project/_project_bloc.phtml' ?>
    <?php endforeach; ?>
</section> 