<section id="#projects_list">
    <p>Voici la liste des projets</p>
    <div class="prj">
        <div class="header">
        <a href="<?=url('project_get',['id'=>1])?>">ztzrrt</a>
            <img src="https://d2homsd77vx6d2.cloudfront.net/cache/8/f/8fd5d7cde7445d0ff2e37d2532268068.jpg" alt=""/>
            <p class="short">petite description supplementaire</p>
            <p class="stats"></p>
        </div>
        <div class="footer">
            <p class="title">PignoufLand</p>
            <p class="category">Cine</p>
            <p class="auteur">Alphonse</p>
            <p class="fonds">25$</p>
            <p class="days">j-25</p>
            <div class="module"></div>
        </div>
    </div>

    <div class="prj">
        <div class="header">
            <img src="https://d2homsd77vx6d2.cloudfront.net/cache/8/f/8fd5d7cde7445d0ff2e37d2532268068.jpg" alt=""/>
            <p class="short">petite description supplementaire</p>
            <p class="stats"></p>
        </div>
        <div class="footer">
            <p class="title">PignoufLand</p>
            <p class="auteur">Alphonse</p>
            <p class="category">Cine</p>
            <p class="fonds">25$</p>
            <p class="days">j-25</p>
            <div class="module"></div>
        </div>
    </div>

    <div class="prj">
        <div class="header">
            <img src="https://d2homsd77vx6d2.cloudfront.net/cache/8/f/8fd5d7cde7445d0ff2e37d2532268068.jpg" alt=""/>
            <p class="short">petite description supplementaire</p>
            <p class="stats"></p>
        </div>
        <div class="footer">
            <p class="title">PignoufLand</p>
            <p class="auteur">Alphonse</p>
            <p class="category">Cine</p>
            <p class="fonds">25$</p>
            <p class="days">j-25</p>
            _ _ _ _ _ _ _ _ _ _ _ _ _ _
        </div>
    </div>

    <div class="prj">
        <div class="header">
            <img src="https://d2homsd77vx6d2.cloudfront.net/cache/8/f/8fd5d7cde7445d0ff2e37d2532268068.jpg" alt=""/>
            <p class="short">petite description supplementaire</p>
            <p class="stats"></p>
        </div>
        <div class="footer">
            <p class="title">PignoufLand</p>
            <p class="auteur">Alphonse</p>
            <p class="category">Cine</p>
            <p class="fonds">25$</p>
            <p class="days">j-25</p>
            
        </div>
    </div>

    <div class="prj">
        <div class="header">
            <img src="https://d2homsd77vx6d2.cloudfront.net/cache/8/f/8fd5d7cde7445d0ff2e37d2532268068.jpg" alt=""/>
            <p class="short">petite description supplementaire</p>
            <p class="stats">32% grâce à 256 donateurs</p>
        </div>
        <div class="footer">
            <p class="title">PignoufLand</p>
            <p class="auteur">Alphonse</p>
            <p class="category">Cine</p>
            <p class="fonds">25$</p>
            <p class="days">j-25</p>
            
        </div>
    </div>
    
</section> 