
<nav class="main">
    <ul>

        <li><a href="/">Home</a></li>
        <li><a href="<?=url('project_list')?>">Voir tous les projets</a></li>
        <li><a href="<?=url('project_rand')?>">Un projet au hasard</a></li>
        <li><a href="<?=url('page_concept')?>">Concept</a></li>
        <li><a href="<?=url('page_stats')?>">Statistiques</a></li>
    </ul>
</nav>

<div class="logo">
    <a href="/"><img src="https://image.freepik.com/vecteurs-libre/dessin-anime-mignon-chouette_33070-2653.jpg" alt="logo"/></a>
</div>

<nav class="admin">
    <ul>
    <?php if($logged): ?>
        <li><?= $user ?> <div class="button_h"><a href="<?=url('project_listmy')?>">Mes projets</a></div></li>
            <li><?= $user ?> <div class="button_h"><a href="<?=url('project_create')?>">Ajouter un projet</a></div></li>
        <?php endif ?>
    

        <?php if($is_admin): ?>
        <?php endif; ?>
            
        <?php if($logged): ?>
            <li><?= $user ?> <div class="button_h"><a href="<?=url('user_disconnect')?>">Déconnexion</a></div></li>
        <?php else: ?>
            <li class="button_h"><div><a href="<?=url('user_subscribe')?>">S'inscrire</a></div></li>
            <li class="button_h"><div><a href="<?=url('user_signin')?>">Connexion</a></div></li>
        <?php endif; ?>
    </ul>
</nav>


