<div class="logo">
    <a href="/"><img src="https://image.freepik.com/vecteurs-libre/dessin-anime-mignon-chouette_33070-2653.jpg" alt="logo"/></a>
</div>
<nav>
    <ul>
        <li>Les projets</li>
        <li>Un projet au hasard</li>
        <li>Concept</li>
        <li>Statistiques</li>
        <li>Contact</li>
    </ul>
</nav>
<p class="connexion">
    <a href="<?=url('user_signin')?>">Connection</a>
    <a href="<?=url('user_subscribe')?>">S'inscrire</a>
</p>