<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Crowdfunding</title>
    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-12/css/all.css" type="text/css" />
    <link rel="stylesheet" href="assets/style/style.css" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <header>
        <?=$header?>
    </header>
    <div class="container">
        <main>
            <?=$content?>
        </main>
    </div>
    <footer>
        <?=$footer?>
    </footer>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="assets/script/script.js"></script>
</body>
</html>