        <div class="prj">
            <div class="header">
                <a href="<?=url('project_get',['id'=>$project['id']])?>">
                    <img src="<?= $project['image_url'] ?>" alt="<?= $project['titre'] ?>"/>
                
                    <p class="short"><?= write($project['resume']) ?></p>
                    <p class="stats">
                        <?= $project['percent'] ?>% 
                        grâce à <?= $project['stats_nb_dons'] ?> donateurs
                    </p>
                </a>
            </div>
            <div class="footer">
                <p class="category"><?= $project['category'] ?></p>
                <p class="titre"><?= write(substr(ucfirst($project['titre']),0,20)) ?></p>
                <p class="createur"><?= write($project['user_login']) ?></p>
                <p class="days"> j-<?= $project['days_reste'] ?> </p>
                <p class="fonds"><?= $project['stats_somme_rec'] ?>/<?= $project['somme_necessaire'] ?>€</p>
                <div class="module" data-percent="<?=$project['percent']>100?100:$project['percent']?>"><div></div></div>
            </div>
        </div>