
<h2><?= $title ?> de votre projet</h2>

<section>
    <?= $msg ?>
    <form action="<?=$_SERVER['REQUEST_URI']?>" method="post" enctype="multipart/form-data" >
        <fieldset>
            <legend>Créateur du projet</legend>
            <label><?=$nom_user?></label>
        </fieldset>

        <fieldset>
            <legend>Détails de votre projet</legend>
            <div><label for="titre">Titre :</label>
                <input type="text" required maxlength="20" name="titre" placeholder="Titre" value="<?=$form['titre']??''?>"/></div>
            <div><label for="description">Description :</label>
                <textarea required name="description" rows="15" placeholder="Description"><?=$form['description']??''?></textarea></div>
            <div><label for="resume">Résumé :</label>
                <input type="text" name="resume" maxlength="50" value="<?=$form['resume']??''?>">
            </div>
            <div><label for="image_url">Image :</label>
                <input <?php if($is_create) echo 'required' ?> type="file" name="image_url" accept=".bmp,.jpg,.jpeg,.gif,.png"></div>
            <?php if(!$is_create): ?>
                <div><label>&nbsp;</label><button type="submit">Enregistrer</button></div>
            <?php endif; ?>
        </fieldset>
        
        <?php if($is_create): ?>
        <fieldset>
            <legend>Réalisation nécessaire</legend>
            <div><label>Fonds nécessaires >800€ :</label>
                <input required min="800" type="number" name="somme" value="<?=$form['somme']??''?>"/></div>
            <div><label>Date de fin (10j-3 mois) :</label>
                <input type="date" required name="date_fin" 
                    <?php $date = isset($form['date_fin']) ? $form['date_fin'] : '' ?>
                    min="<?= (new \DateTime($date))->add(new DateInterval('P10D'))->format('Y-m-d') ?>"
                    max="<?= (new \DateTime($date))->add(new DateInterval('P3M'))->format('Y-m-d') ?>" 
                    value="<?=$form['date_fin']??''?>"/></div>
            <div><label>&nbsp;</label><button type="submit">Enregistrer</button></div>
        </fieldset>
        <?php endif; ?>
    </form>
</section>