
<section class="view">
    <h1><?= $project['titre'] ?></h1>
    <div class="view_prj section_main">
    
        <section class="main">
            <h3><?= $project['titre'] ?></h3>
            <img src="<?= $project['image_url'] ?>" alt="<?= $project['titre'] ?>"/>
            <p class="short"><?= $project['resume'] ?></p>
            <p class="category"> - Catégorie <?= $project['category'] ?> - </p>
            <p class="description"><?= $project['description'] ?></p>
        </section>

        <section class="side">
            <div class="contribute">
                <h3>Progression</h3>
                <p class="stats">
                    <?= $project['percent'] ?>% 
                    grâce à <?= $project['stats_nb_dons'] ?> donateurs</p>
                <p class="days">Il reste <?= $project['days_reste'] ?> jours avant la clôture du projet</p>
                <p class="fonds"><?= $project['stats_somme_rec'] ?>€ collectés sur <?= $project['somme_necessaire'] ?>€</p>
                
                <div id="dialog-message">
                    <h2>Merci de votre contribution</h2>
                    <form action="#" id="form_don">
                        <p>Quel montant souhaitez-vous effectuer pour votre don?</p>
                        <div>Montant du don :</div>
                        <div><input type="number" id="dialog-button-value" min="10" value="50"/></div>
                        <div><button type="button" data-sessionid=<?= session_id() ?>
                            data-id=<?=$project['id']?> id="dialog-button">Envoyer</button></div>
                        <div><img class="paypal" alt="paypal" src="https://www.capitaine-banque.com/wp-content/uploads/2016/09/logo-paypal-300x150.png"/></div>
                        <div>
                            <img class="cb" alt="visa" src="https://www.epargne-en-ligne.net/images/visa-1020x510.png"/>
                            <img class="cb" alt="mastercard" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/MasterCard_Logo.svg/300px-MasterCard_Logo.svg.png"/>
                        </div>
                    </form>
                    
                    <div id="thanks_don">
                        <p>Toute l'équipe de Crownfunding ainsi que les porteurs du projet</p>
                        <p class="title"><?= $project['titre'] ?></p>
                        <p>vous remercient de votre contribution</p>
                        <p><i class="far fa-grin-beam"></i></p>
                    </div>
                </div>
                
                <button type="button" id="contribute">Contribuer</button>
            </div>

            <div class="creator">
                <h3>Créateur du projet</h3>
                <p class="createur"><?= $project['user_login'] ?></p>
                <p class="ville"><?= $project['user_ville'] ?></p>
                <p class="date">Membre depuis le <?= $project['user_date_creation'] ?></p>
            </div>
        </section>
    </div>
</section>

