
<h1>Liste des projets</h1>
    
<section class="list">
    <table>
        <thead>
            <tr>
                <th>Nom du projet</th><th>Résumé</th><th>Fonds collectés</th><th>Jours restants</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($list as $project): ?>
                <tr>
                    <td><?= $project['titre']?></td>
                    <td><?= $project['resume']?></td>
                    <td><?= $project['somme_necessaire']?></td>
                    <td><?= $project['date_fin']?></td>
                    <td><a href="<?=url('project_update_id='.$project['id'])?>">Modifier</a></td>
                    <td><a href="<?=url('project_remove_id='.$project['id'])?>">Supprimer</a></td>
                </tr>
            <?php endforeach; ?>

            <?php if(is_admin() && !empty($others)): 
                echo '<tr><td class="others">Autres projets</td><td colspan="3"></td></tr>'; 
                foreach($others as $project): ?>
                
                <tr>
                    <td><?= $project['titre']?></td>
                    <td><?= $project['resume']?></td>
                    <td><?= $project['somme_necessaire']?></td>
                    <td><?= $project['date_fin']?></td>
                    <td><a href="<?=url('project_update_id='.$project['id'])?>">Modifier</a></td>
                    <td><a href="<?=url('project_remove_id='.$project['id'])?>">Supprimer</a></td>
                </tr>
            <?php endforeach; endif; ?>
        </tbody>
    </table>
</section>