<h1>Connexion</h1>

<section>
    <form action="#" method="post">
        <fieldset>
            <legend>Connexion</legend>
            <div><label>Login :</label><input type-="text" name="login"/></div>
            <div><label>Password :</label><input type-="text" name="password"/></div>
            <div><label>&nbsp;</label><button type="submit">Me connecter</button></div>
        </fieldset>
    </form>
</section>