<h1>Connexion</h1>

<section>
    <form action="#" method="post">
        <fieldset>
            <legend>Connexion</legend>
            <div><label for="login">Login :</label><input type="text" id="login" name="login"/></div>
            <div><label for="password">Password :</label><input type="text" id="password" name="password"/></div>
            <div><label>&nbsp;</label><button type="submit">Me connecter</button></div>
        </fieldset>
    </form>
    (Administrateur: login: abs, password: abs)
</section>