<h1>Inscription</h1>

<section>
    <div class="message"><?= $msg; ?></div>
    <form action="<?=url('user_subscribe')?>" method="post">
        <fieldset>
            <legend>Informations de contact</legend>
            <div><label for="nom">Nom :</label><input type="text" id="nom" name="nom" value="<?=$post['nom']??''?>"/></div>
            <div><label for="prenom">Prénom :</label><input type="text" id="prenom" name="prenom" value="<?=$post['prenom']??''?>"/></div>
            <div><label for="email">Email :</label><input type="text" id="email" name="email" value="<?=$post['email']??''?>"/></div>
            <div><label for="telephone">Téléphone :</label><input type="text" id="telephone" name="telephone" value="<?=$post['telephone']??''?>"/></div>
            <div><label for="ville">Ville :</label><input type="text" id="ville" name="ville" value="<?=$post['ville']??''?>"/></div>
        </fieldset>
        <fieldset>
            <legend>Informations de connexion</legend>
            <div><label for="login">Login :</label><input type="text" id="login" name="login" value="<?=$post['login']??''?>"/></div>
            <div><label for="password">Mot de passe : </label><input type="text" id="password" name="password"/></div>
            <div><label for="retype_password">Retapez le mot de passe : </label>
                <input id="retype_password" type="text" name="retype_password"/></div>
            <div><button type="submit">Créer mon compte</button></div>
            <div><a href="<?=url('')?>"><button type="button">Annuler</button></a></div>
        </fieldset>
    </form>
</section>