<h1>S'inscrire</h1>
<div class="message"><?= $msg; ?></div>
<form action="" method="post">
    <p><label for="login">Login: </label><input type="text" name="login" value="<?=$post['login']??''?>"/></p>
    <p><label for="login">Mot de passe: </label><input type="text" name="password"/></p>
    <p><label for="login">Retapez votre mot de passe: </label><input type="text" name="retype_password"/></p>
    <p><button type="submit">Créer mon compte</button></p>
</form>